### ISSUE TITLE
changing title color suggestion

### ISSUE THREAD

**Issue by nguyentranenvoyair** [ntran0429/git-crash-course#1]
I suggest we change the title color like so:

``` css
h1 {
  color: #c38b2a;
}
```
